### ISSUE TITLE
`ScrollingPageControl` is not currently importable

### ISSUE THREAD

**Issue by wmcginty** [BottleRocketStudios/iOS-UtiliKit#108]
ScrollingPageControl is currently unable to be imported (it isn't part of the Core subspec and has no separate subspec. With the changes to UIPageControl in iOS 14 - it may be time to deprecate / remove anyway?

**Comment by br-earl-gaspard** [comment]
ScrollingPageControl has been added as a subspec for CocoaPods and a library for Swift Packages.
