### ISSUE TITLE
"children" is a namespace collision in UIViewController with Xcode 10

### ISSUE THREAD

**Issue by rmirabelli** [BottleRocketStudios/iOS-UtiliKit#22]
This used to be "childViewControllers".

This should be straightforward.

**Comment by wmcginty** [comment]
Any idea for a new name? Just reversing them doesn't really work, as childViewControllers isn't exactly accurate.

**Comment by tylermilner** [comment]
Fixed by #23. Looks like we're going with `managedChildren`, which works for me! 👍
