### ISSUE TITLE
Add more documentation around preferred ContainerViewController usage

### ISSUE THREAD

**Issue by tylermilner** [BottleRocketStudios/iOS-UtiliKit#59]
What's the "right" way to use `ContainerViewController`? Should you subclass it or should you use it with composition? Are there benefits doing it one way vs the other? I think I've usually seen it used with composition since subclassing requires you to hook into the view lifecycle methods at just the right moment to populate the `managedChildren` property. We should improve our documentation with the tradeoffs of each approach, and make our preferred approach known.

**Comment by wmcginty** [comment]
Transferred to https://github.com/BottleRocketStudios/iOS-Container/issues/4
