### ISSUE TITLE
Add static string URL initializer?

### ISSUE THREAD

**Issue by tylermilner** [BottleRocketStudios/iOS-UtiliKit#60]
Saw how John Sundell uses a `URL` initializer with a `staticString` parameter to make it easy to create `URL`s that are baked in to app at build-time. We should consider adding this to either UtiliKit or Hyperspace.

https://www.swiftbysundell.com/posts/constructing-urls-in-swift#static-urls

**Comment by wmcginty** [comment]
Implemented in #66
