### ISSUE TITLE
Container - completion block in transitionToController no longer called

### ISSUE THREAD

**Issue by earlgaspard** [BottleRocketStudios/iOS-UtiliKit#75]
While using 1.6.0, I discovered that the completion block in `transitionToController` was no longer being called. My work around was to implement the delegate callback:  `containerViewController(_ container: ContainerViewController, didFinishTransitioningFrom`
```
containerViewController.transitionToController(for: child) { _ in
   // does not get hit
}
```

**Comment by wmcginty** [comment]
@earlgaspard If you switch to use #76  does it fix your issue?

**Comment by wmcginty** [comment]
Should be addressed by #76. @earlgaspard can you confirm and close?

**Comment by earlgaspard** [comment]
I can check #76 later today and see if it works.

**Comment by earlgaspard** [comment]
Well, it does not look like it is going to be today. Sometime soon.

**Comment by wmcginty** [comment]
I have not heard this happening, going to close.
