### ISSUE TITLE
Child views not being configured

### ISSUE THREAD

**Issue by brayden4012** [BottleRocketStudios/iOS-UtiliKit#80]
Whenever I called the `transitionToController(for child:completion:)` method, only my first view controller is constrained within the container view controller. All subsequent calls to the method does not configure the other view controllers to fit inside the container view.

[UtiliKitContainerViewBug.zip](https://github.com/BottleRocketStudios/iOS-UtiliKit/files/3611030/UtiliKitContainerViewBug.zip)

**Comment by wmcginty** [comment]
Hey @brayden4012 thanks for the report - I think this should be fixed by #79 . Do you think you could run the sample project against the `transitionIssue_iOS13` to see if that fixes it?

**Comment by brayden4012** [comment]
Worked like a charm on my test project! However I'm not seeing the same
results in the project I'm currently working on. The only difference
between the two is that I'm initializing 3 pods from UtiliKit in my current
project. In the podfile, I call all 3 of those pods from the same branch in
the github repo. Any thoughts?

**Comment by wmcginty** [comment]
Are you seeing any warnings in the console like `unbalanced calls to begin/end appearance transition for view controller` ? That's usually indicative of something going wrong in the container's transition animator.

**Comment by brayden4012** [comment]
I havent seen any errors

**Comment by brayden4012** [comment]
*warnings

**Comment by wmcginty** [comment]
This looks to have been resolved. Closing.
