### ISSUE TITLE
ContainerViewController - Add ability to transition to empty child

### ISSUE THREAD

**Issue by tylermilner** [BottleRocketStudios/iOS-UtiliKit#85]
Currently, it doesn't seem like it's possible to remove a child from `ContainerViewController`. You seem to only be able to transition to a new child view controller (i.e. `transitionToController(for:completion:)` requires a non-nil `ManagedChild`).

I've run into a situation where I'd like to "reset" the ContainerViewController by removing all of its managed children, going back to an empty state where no child is displayed (i.e. what you get if you just initialize an empty `ContainerViewController()`).

Any suggestions for current workarounds are welcome.

**Comment by wmcginty** [comment]
Not sure there is a current work around for this - I would add it would be nice to add a property to the VC where you can specify a behavior that describes "what should I do with all the _other_ children I have"?

**Comment by wmcginty** [comment]
Transferred to: https://github.com/BottleRocketStudios/iOS-Container/issues/3
