### ISSUE TITLE
Obfuscation - Add more examples

### ISSUE THREAD

**Issue by earlgaspard** [BottleRocketStudios/iOS-UtiliKit#86]
Issues:
- The Obfuscation section in the Readme is lacking in examples.
- Had to look into the tests for some samples of how this was used.

Action Items:
- [x] Add more examples to the Readme for Obfuscation and ObfuscatedKey.

**Comment by br-earl-gaspard** [comment]
Resolved in https://github.com/BottleRocketStudios/iOS-UtiliKit/pull/118.
