### ISSUE TITLE
Move ContainerView code to a separate open source repo

### ISSUE THREAD

**Issue by earlgaspard** [BottleRocketStudios/iOS-UtiliKit#91]
Since ContainerView has become a large majority of the code base in UtiliKit, it has been decided that it should be moved to its own repo. The progress toward that has begun. Once the new repo is live, ContainerView should be deprecated in UtiliKit and later removed completely.

**Comment by wmcginty** [comment]
This is in the process of being released: https://github.com/BottleRocketStudios/iOS-Container

**Comment by wmcginty** [comment]
https://github.com/BottleRocketStudios/iOS-Container/releases/tag/1.0.0
